# Pandas

In [185]:
import pandas as pd

## Series
 > labelled 1-Dimensional array

In [186]:

data = [100, 101, 102]
series = pd.Series(data) # constructor so capital S
print(series)

data = [100.1, 101.2, 102.3]
series = pd.Series(data) 
print(series)

data = ["A", "B", "C"]
series = pd.Series(data) 
print(series)

data = [True, False, True]
series = pd.Series(data) 
print(series)

0    100
1    101
2    102
dtype: int64
0    100.1
1    101.2
2    102.3
dtype: float64
0    A
1    B
2    C
dtype: object
0     True
1    False
2     True
dtype: bool

In [187]:

data = [100, 101, 102,55, 45]
series = pd.Series(data, ["a","b","c", "d", "e"]) # with labels

print(series.loc["a"]) # loc = location object
series.loc["a"]=200
series

100

a    200
b    101
c    102
d     55
e     45
dtype: int64

In [188]:
print(series.iloc[0])
series.iloc[0]=400
series

200

a    400
b    101
c    102
d     55
e     45
dtype: int64

In [189]:
series[series >=101]

a    400
b    101
c    102
dtype: int64

In [190]:
calaries={"Day 1":100, "Day 2":200, "Day 3": 300}
series = pd.Series(calaries)
series

Day 1    100
Day 2    200
Day 3    300
dtype: int64

In [191]:
print(series["Day 1"])
series["Day 2"]+=500
series

100

Day 1    100
Day 2    700
Day 3    300
dtype: int64

## Data Frames
>
> Tabular data structure
> 2 Dimensional

In [192]:
users = {
          "Name":["Ramu", "Ravinder", "Reddy"],
          "Age": [28, 29, 25]
         }

df = pd.DataFrame(users)
df

       Name  Age
0      Ramu   28
1  Ravinder   29
2     Reddy   25

In [193]:
df = pd.DataFrame(users, index=["User 1", "User 2", "User 3"])
df

            Name  Age
User 1      Ramu   28
User 2  Ravinder   29
User 3     Reddy   25

In [194]:
df.loc["User 1"]

Name    Ramu
Age       28
Name: User 1, dtype: object

In [195]:
df.iloc[1]

Name    Ravinder
Age           29
Name: User 2, dtype: object

### Adding a new column

In [196]:

df["Job"]=["Husband", "Develoer", "Son"] # the values should match columns
df

            Name  Age       Job
User 1      Ramu   28   Husband
User 2  Ravinder   29  Develoer
User 3     Reddy   25       Son

### Adding a new row

In [197]:
new_rows = pd.DataFrame([{"Name":"Raaji", "Age":25, "Job":"Manager"}])
df = pd.concat([df, new_rows])
df

            Name  Age       Job
User 1      Ramu   28   Husband
User 2  Ravinder   29  Develoer
User 3     Reddy   25       Son
0          Raaji   25   Manager

In [198]:
new_rows = pd.DataFrame([{"Name":"Coder", "Age":28, "Job":"Dev"}], index=["User 5"])
df = pd.concat([df, new_rows])
df

            Name  Age       Job
User 1      Ramu   28   Husband
User 2  Ravinder   29  Develoer
User 3     Reddy   25       Son
0          Raaji   25   Manager
User 5     Coder   28       Dev

In [199]:
new_rows = pd.DataFrame([
    {"Name":"Coder-1", "Age":29, "Job":"Dev-1"},
    {"Name":"Coder-2", "Age":22, "Job":"Dev-2"}
    ], 
    index=["User 6", "User 7"])
df = pd.concat([df, new_rows])
df

            Name  Age       Job
User 1      Ramu   28   Husband
User 2  Ravinder   29  Develoer
User 3     Reddy   25       Son
0          Raaji   25   Manager
User 5     Coder   28       Dev
User 6   Coder-1   29     Dev-1
User 7   Coder-2   22     Dev-2

In [200]:
# Create a simple DataFrame
df = pd.DataFrame(
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
    columns=["A", "B", "C"],
    index=["x", "y", "z", "zz"]
)
df

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [201]:
# Display the first few rows
df.head(2) # df.head()

   A  B  C
x  1  2  3
y  4  5  6

In [202]:
# Display the last two rows
df.tail(2)

     A   B   C
z    7   8   9
zz  10  11  12

## Importing ( CSV, JSON )

In [203]:
# Load data from CSV
noc_regions = pd.read_csv('./data/noc_regions.csv')
noc_regions # prints only top5 & bottom5, if data is largs



# Load data from Parquet
# results = pd.read_parquet('./data/results.parquet')

# Load data from Excel
# olympics_data = pd.read_excel('./data/olympics-data.xlsx', sheet_name="results")

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

In [204]:
print(noc_regions.to_string()) # to print all  # ***

     NOC                            region                        notes
0    AFG                       Afghanistan                          NaN
1    AHO                           Curacao         Netherlands Antilles
2    ALB                           Albania                          NaN
3    ALG                           Algeria                          NaN
4    AND                           Andorra                          NaN
5    ANG                            Angola                          NaN
6    ANT                           Antigua          Antigua and Barbuda
7    ANZ                         Australia                  Australasia
8    ARG                         Argentina                          NaN
9    ARM                           Armenia                          NaN
10   ARU                             Aruba                          NaN
11   ASA                    American Samoa                          NaN
12   AUS                         Australia                          NaN
13   AUT                           Austria                          NaN
14   AZE                        Azerbaijan                          NaN
15   BAH                           Bahamas                          NaN
16   BAN                        Bangladesh                          NaN
17   BAR                          Barbados                          NaN
18   BDI                           Burundi                          NaN
19   BEL                           Belgium                          NaN
20   BEN                             Benin                          NaN
21   BER                           Bermuda                          NaN
22   BHU                            Bhutan                          NaN
23   BIH            Bosnia and Herzegovina                          NaN
24   BIZ                            Belize                          NaN
25   BLR                           Belarus                          NaN
26   BOH                    Czech Republic                      Bohemia
27   BOL                            Boliva                          NaN
28   BOT                          Botswana                          NaN
29   BRA                            Brazil                          NaN
30   BRN                           Bahrain                          NaN
31   BRU                            Brunei                          NaN
32   BUL                          Bulgaria                          NaN
33   BUR                      Burkina Faso                          NaN
34   CAF          Central African Republic                          NaN
35   CAM                          Cambodia                          NaN
36   CAN                            Canada                          NaN
37   CAY                    Cayman Islands                          NaN
38   CGO                 Republic of Congo                          NaN
39   CHA                              Chad                          NaN
40   CHI                             Chile                          NaN
41   CHN                             China                          NaN
42   CIV                       Ivory Coast                          NaN
43   CMR                          Cameroon                          NaN
44   COD  Democratic Republic of the Congo                          NaN
45   COK                      Cook Islands                          NaN
46   COL                          Colombia                          NaN
47   COM                           Comoros                          NaN
48   CPV                        Cape Verde                          NaN
49   CRC                        Costa Rica                          NaN
50   CRO                           Croatia                          NaN
51   CRT                            Greece                        Crete
52   CUB                              Cuba                          NaN
53   CYP                            Cyprus                          NaN
54   CZE                    Czech Republic                          NaN
55   DEN                           Denmark                          NaN
56   DJI                          Djibouti                          NaN
57   DMA                          Dominica                          NaN
58   DOM                Dominican Republic                          NaN
59   ECU                           Ecuador                          NaN
60   EGY                             Egypt                          NaN
61   ERI                           Eritrea                          NaN
62   ESA                       El Salvador                          NaN
63   ESP                             Spain                          NaN
64   EST                           Estonia                          NaN
65   ETH                          Ethiopia                          NaN
66   EUN                            Russia                          NaN
67   FIJ                              Fiji                          NaN
68   FIN                           Finland                          NaN
69   FRA                            France                          NaN
70   FRG                           Germany                          NaN
71   FSM                        Micronesia                          NaN
72   GAB                             Gabon                          NaN
73   GAM                            Gambia                          NaN
74   GBR                                UK                          NaN
75   GBS                     Guinea-Bissau                          NaN
76   GDR                           Germany                          NaN
77   GEO                           Georgia                          NaN
78   GEQ                 Equatorial Guinea                          NaN
79   GER                           Germany                          NaN
80   GHA                             Ghana                          NaN
81   GRE                            Greece                          NaN
82   GRN                           Grenada                          NaN
83   GUA                         Guatemala                          NaN
84   GUI                            Guinea                          NaN
85   GUM                              Guam                          NaN
86   GUY                            Guyana                          NaN
87   HAI                             Haiti                          NaN
88   HKG                             China                    Hong Kong
89   HON                          Honduras                          NaN
90   HUN                           Hungary                          NaN
91   INA                         Indonesia                          NaN
92   IND                             India                          NaN
93   IOA       Individual Olympic Athletes  Individual Olympic Athletes
94   IRI                              Iran                          NaN
95   IRL                           Ireland                          NaN
96   IRQ                              Iraq                          NaN
97   ISL                           Iceland                          NaN
98   ISR                            Israel                          NaN
99   ISV                Virgin Islands, US               Virgin Islands
100  ITA                             Italy                          NaN
101  IVB           Virgin Islands, British                          NaN
102  JAM                           Jamaica                          NaN
103  JOR                            Jordan                          NaN
104  JPN                             Japan                          NaN
105  KAZ                        Kazakhstan                          NaN
106  KEN                             Kenya                          NaN
107  KGZ                        Kyrgyzstan                          NaN
108  KIR                          Kiribati                          NaN
109  KOR                       South Korea                          NaN
110  KOS                            Kosovo                          NaN
111  KSA                      Saudi Arabia                          NaN
112  KUW                            Kuwait                          NaN
113  LAO                              Laos                          NaN
114  LAT                            Latvia                          NaN
115  LBA                             Libya                          NaN
116  LBR                           Liberia                          NaN
117  LCA                       Saint Lucia                          NaN
118  LES                           Lesotho                          NaN
119  LIB                           Lebanon                          NaN
120  LIE                     Liechtenstein                          NaN
121  LTU                         Lithuania                          NaN
122  LUX                        Luxembourg                          NaN
123  MAD                        Madagascar                          NaN
124  MAL                          Malaysia                          NaN
125  MAR                           Morocco                          NaN
126  MAS                          Malaysia                          NaN
127  MAW                            Malawi                          NaN
128  MDA                           Moldova                          NaN
129  MDV                          Maldives                          NaN
130  MEX                            Mexico                          NaN
131  MGL                          Mongolia                          NaN
132  MHL                  Marshall Islands                          NaN
133  MKD                         Macedonia                          NaN
134  MLI                              Mali                          NaN
135  MLT                             Malta                          NaN
136  MNE                        Montenegro                          NaN
137  MON                            Monaco                          NaN
138  MOZ                        Mozambique                          NaN
139  MRI                         Mauritius                          NaN
140  MTN                        Mauritania                          NaN
141  MYA                           Myanmar                          NaN
142  NAM                           Namibia                          NaN
143  NBO                          Malaysia                 North Borneo
144  NCA                         Nicaragua                          NaN
145  NED                       Netherlands                          NaN
146  NEP                             Nepal                          NaN
147  NFL                            Canada                 Newfoundland
148  NGR                           Nigeria                          NaN
149  NIG                             Niger                          NaN
150  NOR                            Norway                          NaN
151  NRU                             Nauru                          NaN
152  NZL                       New Zealand                          NaN
153  OMA                              Oman                          NaN
154  PAK                          Pakistan                          NaN
155  PAN                            Panama                          NaN
156  PAR                          Paraguay                          NaN
157  PER                              Peru                          NaN
158  PHI                       Philippines                          NaN
159  PLE                         Palestine                          NaN
160  PLW                             Palau                          NaN
161  PNG                  Papua New Guinea                          NaN
162  POL                            Poland                          NaN
163  POR                          Portugal                          NaN
164  PRK                       North Korea                          NaN
165  PUR                       Puerto Rico                          NaN
166  QAT                             Qatar                          NaN
167  RHO                          Zimbabwe                          NaN
168  ROT                               NaN         Refugee Olympic Team
169  ROU                           Romania                          NaN
170  RSA                      South Africa                          NaN
171  RUS                            Russia                          NaN
172  RWA                            Rwanda                          NaN
173  SAA                           Germany                          NaN
174  SAM                             Samoa                          NaN
175  SCG                            Serbia        Serbia and Montenegro
176  SEN                           Senegal                          NaN
177  SEY                        Seychelles                          NaN
178  SIN                         Singapore                          NaN
179  SKN                       Saint Kitts     Turks and Caicos Islands
180  SLE                      Sierra Leone                          NaN
181  SLO                          Slovenia                          NaN
182  SMR                        San Marino                          NaN
183  SOL                   Solomon Islands                          NaN
184  SOM                           Somalia                          NaN
185  SRB                            Serbia                          NaN
186  SRI                         Sri Lanka                          NaN
187  SSD                       South Sudan                          NaN
188  STP             Sao Tome and Principe                          NaN
189  SUD                             Sudan                          NaN
190  SUI                       Switzerland                          NaN
191  SUR                          Suriname                          NaN
192  SVK                          Slovakia                          NaN
193  SWE                            Sweden                          NaN
194  SWZ                         Swaziland                          NaN
195  SYR                             Syria                          NaN
196  TAN                          Tanzania                          NaN
197  TCH                    Czech Republic                          NaN
198  TGA                             Tonga                          NaN
199  THA                          Thailand                          NaN
200  TJK                        Tajikistan                          NaN
201  TKM                      Turkmenistan                          NaN
202  TLS                       Timor-Leste                          NaN
203  TOG                              Togo                          NaN
204  TPE                            Taiwan                          NaN
205  TTO                          Trinidad          Trinidad and Tobago
206  TUN                           Tunisia                          NaN
207  TUR                            Turkey                          NaN
208  TUV                               NaN                       Tuvalu
209  UAE              United Arab Emirates                          NaN
210  UAR                             Syria         United Arab Republic
211  UGA                            Uganda                          NaN
212  UKR                           Ukraine                          NaN
213  UNK                               NaN                      Unknown
214  URS                            Russia                          NaN
215  URU                           Uruguay                          NaN
216  USA                               USA                          NaN
217  UZB                        Uzbekistan                          NaN
218  VAN                           Vanuatu                          NaN
219  VEN                         Venezuela                          NaN
220  VIE                           Vietnam                          NaN
221  VIN                     Saint Vincent                          NaN
222  VNM                           Vietnam                          NaN
223  WIF                          Trinidad       West Indies Federation
224  YAR                             Yemen                  North Yemen
225  YEM                             Yemen                          NaN
226  YMD                             Yemen                  South Yemen
227  YUG                            Serbia                   Yugoslavia
228  ZAM                            Zambia                          NaN
229  ZIM                          Zimbabwe                          NaN

In [243]:
# Json
users  = pd.read_json('./data/users.json')

users

,id,name,age,email,job
0,1,Ravi Kumar,29,1ravi.kumar@example.com,Software Developer
1,1,Ravi Kumar,29,ravi.kumar@example.com,Software Developer
2,2,Kiran Reddy,32,kiran.reddy@example.com,QA Engineer
3,3,Suma Priya,26,suma.priya@example.com,UI/UX Designer
4,4,Rahul Sharma,30,rahul.sharma@example.com,Data Analyst
5,5,Akhil Verma,27,akhil.verma@example.com,Machine Learning Engineer
6,6,Pooja Devi,24,pooja.devi@example.com,Frontend Developer
7,7,Sai Teja,31,sai.teja@example.com,Project Manager
8,8,Meena Singh,28,meena.singh@example.com,Backend Developer
9,9,Aditya Raj,35,aditya.raj@example.com,Team Lead
10,10,Divya Gupta,23,divya.gupta@example.com,HR Coordinator
11,11,Harika Nair,27,harika.nair@example.com,Content Writer
12,12,Vijay Kumar,33,vijay.kumar@example.com,Cloud Architect
13,13,Swathi Rao,25,swathi.rao@example.com,Cyber Security Analyst
14,14,Naveen Chandra,29,naveen.chandra@example.com,Full Stack Developer
15,15,Niharika Sharma,22,niharika.sharma@example.com,Graphic Designer
16,16,Sandeep Joshi,34,sandeep.joshi@example.com,DevOps Engineer
17,17,Karthik R,28,karthik.r@example.com,Android Developer
18,18,Ritika Jain,26,ritika.jain@example.com,Product Manager
19,19,Yashwant Singh,37,yashwant.singh@example.com,IT Consultant
20,20,Lavanya B,24,lavanya.b@example.com,Digital Marketer
21,21,Rohit Kulkarni,32,rohit.kulkarni@example.com,Solutions Architect
22,22,Preethi V,30,preethi.v@example.com,Business Analyst
23,23,Suhas Rao,27,suhas.rao@example.com,Financial Analyst
24,24,Rohan Mehta,29,rohan.mehta@example.com,Blockchain Developer
25,25,Sneha Kapoor,23,sneha.kapoor@example.com,Data Scientist
26,26,Anil Pandey,36,anil.pandey@example.com,Network Administrator
27,27,Sravani M,28,sravani.m@example.com,Frontend Engineer
28,28,Dinesh Varma,31,dinesh.varma@example.com,System Analyst
29,29,Anusha Shetty,25,anusha.shetty@example.com,Recruiter
30,30,Mahesh Patil,34,mahesh.patil@example.com,Database Administrator
31,28,Dinesh Varma,31,dinesh.varma@example.com,System Analyst
32,29,Anusha Shetty,25,anusha.shetty@example.com,Recruiter
33,30,Mahesh Patil,34,mahesh.patil@example.com,Database Administrator

### Data Selection

In [206]:
users["name"]

0         1Ravi Kumar
1          Ravi Kumar
2         Kiran Reddy
3          Suma Priya
4        Rahul Sharma
5         Akhil Verma
6          Pooja Devi
7            Sai Teja
8         Meena Singh
9          Aditya Raj
10        Divya Gupta
11        Harika Nair
12        Vijay Kumar
13         Swathi Rao
14     Naveen Chandra
15    Niharika Sharma
16      Sandeep Joshi
17          Karthik R
18        Ritika Jain
19     Yashwant Singh
20          Lavanya B
21     Rohit Kulkarni
22          Preethi V
23          Suhas Rao
24        Rohan Mehta
25       Sneha Kapoor
26        Anil Pandey
27          Sravani M
28       Dinesh Varma
29      Anusha Shetty
30       Mahesh Patil
31      1Dinesh Varma
32     1Anusha Shetty
33      1Mahesh Patil
Name: name, dtype: object

In [207]:
users[["name","age", "email"]]

               name  age                        email
0       1Ravi Kumar   29      1ravi.kumar@example.com
1        Ravi Kumar   29       ravi.kumar@example.com
2       Kiran Reddy   32      kiran.reddy@example.com
3        Suma Priya   26       suma.priya@example.com
4      Rahul Sharma   30     rahul.sharma@example.com
5       Akhil Verma   27      akhil.verma@example.com
6        Pooja Devi   24       pooja.devi@example.com
7          Sai Teja   31         sai.teja@example.com
8       Meena Singh   28      meena.singh@example.com
9        Aditya Raj   35       aditya.raj@example.com
10      Divya Gupta   23      divya.gupta@example.com
11      Harika Nair   27      harika.nair@example.com
12      Vijay Kumar   33      vijay.kumar@example.com
13       Swathi Rao   25       swathi.rao@example.com
14   Naveen Chandra   29   naveen.chandra@example.com
15  Niharika Sharma   22  niharika.sharma@example.com
16    Sandeep Joshi   34    sandeep.joshi@example.com
17        Karthik R   28        karthik.r@example.com
18      Ritika Jain   26      ritika.jain@example.com
19   Yashwant Singh   37   yashwant.singh@example.com
20        Lavanya B   24        lavanya.b@example.com
21   Rohit Kulkarni   32   rohit.kulkarni@example.com
22        Preethi V   30        preethi.v@example.com
23        Suhas Rao   27        suhas.rao@example.com
24      Rohan Mehta   29      rohan.mehta@example.com
25     Sneha Kapoor   23     sneha.kapoor@example.com
26      Anil Pandey   36      anil.pandey@example.com
27        Sravani M   28        sravani.m@example.com
28     Dinesh Varma   31     dinesh.varma@example.com
29    Anusha Shetty   25    anusha.shetty@example.com
30     Mahesh Patil   34     mahesh.patil@example.com
31    1Dinesh Varma   31     dinesh.varma@example.com
32   1Anusha Shetty   25    anusha.shetty@example.com
33    1Mahesh Patil   34     mahesh.patil@example.com

In [208]:
## Row Selection
users.loc[0]

id                             1
name                 1Ravi Kumar
age                           29
email    1ravi.kumar@example.com
job           Software Developer
Name: 0, dtype: object

In [245]:
users  = pd.read_json('./data/users.json').set_index("name")

users

,id,age,email,job
name,,,,
Ravi Kumar,1,29,ravi.kumar@example.com,Software Developer
Ravi Kumar,1,29,ravi.kumar@example.com,Software Developer
Kiran Reddy,2,32,kiran.reddy@example.com,QA Engineer
Suma Priya,3,26,suma.priya@example.com,UI/UX Designer
Rahul Sharma,4,30,rahul.sharma@example.com,Data Analyst
Akhil Verma,5,27,akhil.verma@example.com,Machine Learning Engineer
Pooja Devi,6,24,pooja.devi@example.com,Frontend Developer
Sai Teja,7,31,sai.teja@example.com,Project Manager
Meena Singh,8,28,meena.singh@example.com,Backend Developer
Aditya Raj,9,35,aditya.raj@example.com,Team Lead
Divya Gupta,10,23,divya.gupta@example.com,HR Coordinator
Harika Nair,11,27,harika.nair@example.com,Content Writer
Vijay Kumar,12,33,vijay.kumar@example.com,Cloud Architect
Swathi Rao,13,25,swathi.rao@example.com,Cyber Security Analyst
Naveen Chandra,14,29,naveen.chandra@example.com,Full Stack Developer
Niharika Sharma,15,22,niharika.sharma@example.com,Graphic Designer
Sandeep Joshi,16,34,sandeep.joshi@example.com,DevOps Engineer
Karthik R,17,28,karthik.r@example.com,Android Developer
Ritika Jain,18,26,ritika.jain@example.com,Product Manager
Yashwant Singh,19,37,yashwant.singh@example.com,IT Consultant
Lavanya B,20,24,lavanya.b@example.com,Digital Marketer
Rohit Kulkarni,21,32,rohit.kulkarni@example.com,Solutions Architect
Preethi V,22,30,preethi.v@example.com,Business Analyst
Suhas Rao,23,27,suhas.rao@example.com,Financial Analyst
Rohan Mehta,24,29,rohan.mehta@example.com,Blockchain Developer
Sneha Kapoor,25,23,sneha.kapoor@example.com,Data Scientist
Anil Pandey,26,36,anil.pandey@example.com,Network Administrator
Sravani M,27,28,sravani.m@example.com,Frontend Engineer
Dinesh Varma,28,31,dinesh.varma@example.com,System Analyst
Anusha Shetty,29,25,anusha.shetty@example.com,Recruiter
Mahesh Patil,30,34,mahesh.patil@example.com,Database Administrator
Dinesh Varma,28,31,dinesh.varma@example.com,System Analyst
Anusha Shetty,29,25,anusha.shetty@example.com,Recruiter
Mahesh Patil,30,34,mahesh.patil@example.com,Database Administrator

In [210]:
users.loc["Mahesh Patil"]

id                             30
age                            34
email    mahesh.patil@example.com
job        Database Administrator
Name: Mahesh Patil, dtype: object

In [211]:
users.loc["Mahesh Patil",["age","email"]]

age                            34
email    mahesh.patil@example.com
Name: Mahesh Patil, dtype: object

In [212]:
users.loc["Karthik R":"Mahesh Patil",["age","email"]] # from:to

                age                       email
name
Karthik R        28       karthik.r@example.com
Ritika Jain      26     ritika.jain@example.com
Yashwant Singh   37  yashwant.singh@example.com
Lavanya B        24       lavanya.b@example.com
Rohit Kulkarni   32  rohit.kulkarni@example.com
Preethi V        30       preethi.v@example.com
Suhas Rao        27       suhas.rao@example.com
Rohan Mehta      29     rohan.mehta@example.com
Sneha Kapoor     23    sneha.kapoor@example.com
Anil Pandey      36     anil.pandey@example.com
Sravani M        28       sravani.m@example.com
Dinesh Varma     31    dinesh.varma@example.com
Anusha Shetty    25   anusha.shetty@example.com
Mahesh Patil     34    mahesh.patil@example.com

In [213]:
users[0:2]

             id  age                    email                 job
name
1Ravi Kumar   1   29  1ravi.kumar@example.com  Software Developer
Ravi Kumar    1   29   ravi.kumar@example.com  Software Developer

In [214]:
users.iloc[0:30:2, 0:2]  # row-from:to:step, column-from:to:step

                id  age
name
1Ravi Kumar      1   29
Kiran Reddy      2   32
Rahul Sharma     4   30
Pooja Devi       6   24
Meena Singh      8   28
Divya Gupta     10   23
Vijay Kumar     12   33
Naveen Chandra  14   29
Sandeep Joshi   16   34
Ritika Jain     18   26
Lavanya B       20   24
Preethi V       22   30
Rohan Mehta     24   29
Anil Pandey     26   36
Dinesh Varma    28   31

In [ ]:
name = input("Enter a name: ")
try:
    print(users.loc[name])
except KeyError:
    print(f"{name} not found")

 not found

## Filtering

In [216]:
users[users["age"]>35]

                id  age                       email                    job
name
Yashwant Singh  19   37  yashwant.singh@example.com          IT Consultant
Anil Pandey     26   36     anil.pandey@example.com  Network Administrator

In [217]:
users[users["age"]==35]

            id  age                   email        job
name
Aditya Raj   9   35  aditya.raj@example.com  Team Lead

In [218]:

users[(users["age"]==35) | (users["id"]==21)]

# users[(users["age"]==35) | (users["name"]=="Rohit Kulkarni")] # gives error, bcz name is index, use loc

                id  age                       email                  job
name
Aditya Raj       9   35      aditya.raj@example.com            Team Lead
Rohit Kulkarni  21   32  rohit.kulkarni@example.com  Solutions Architect

## Agrregate Functions
>
> Summrizes to a single value

In [219]:
users.mean(numeric_only=True)

id     16.264706
age    28.941176
dtype: float64

In [220]:
users.sum(numeric_only=True)

id     553
age    984
dtype: int64

In [221]:
users.max(numeric_only=True)

id     30
age    37
dtype: int64

In [222]:
users.min(numeric_only=True)

id      1
age    22
dtype: int64

In [223]:
users.count()

id       34
age      34
email    34
job      34
dtype: int64

In [224]:
## Single Column Aggrregate Functions
users["age"].mean()

np.float64(28.941176470588236)

In [225]:
users["age"].sum()

np.int64(984)

### Group By Agrregate Function

In [226]:
group_by = users.groupby("age") # object
group_by["id"].mean()

age
22    15.000000
23    17.500000
24    13.000000
25    23.666667
26    10.500000
27    13.000000
28    17.333333
29    10.000000
30    13.000000
31    21.000000
32    11.500000
33    12.000000
34    25.333333
35     9.000000
36    26.000000
37    19.000000
Name: id, dtype: float64

In [227]:
group_by = users.groupby("job") # object
group_by["age"].count()

job
Android Developer            1
Backend Developer            1
Blockchain Developer         1
Business Analyst             1
Cloud Architect              1
Content Writer               1
Cyber Security Analyst       1
Data Analyst                 1
Data Scientist               1
Database Administrator       2
DevOps Engineer              1
Digital Marketer             1
Financial Analyst            1
Frontend Developer           1
Frontend Engineer            1
Full Stack Developer         1
Graphic Designer             1
HR Coordinator               1
IT Consultant                1
Machine Learning Engineer    1
Network Administrator        1
Product Manager              1
Project Manager              1
QA Engineer                  1
Recruiter                    2
Software Developer           2
Solutions Architect          1
System Analyst               2
Team Lead                    1
UI/UX Designer               1
Name: age, dtype: int64

In [228]:
users.groupby("age")["job"].agg(list) # result is series

age
22                                   [Graphic Designer]
23                     [HR Coordinator, Data Scientist]
24               [Frontend Developer, Digital Marketer]
25       [Cyber Security Analyst, Recruiter, Recruiter]
26                    [UI/UX Designer, Product Manager]
27    [Machine Learning Engineer, Content Writer, Fi...
28    [Backend Developer, Android Developer, Fronten...
29    [Software Developer, Software Developer, Full ...
30                     [Data Analyst, Business Analyst]
31    [Project Manager, System Analyst, System Analyst]
32                   [QA Engineer, Solutions Architect]
33                                    [Cloud Architect]
34    [DevOps Engineer, Database Administrator, Data...
35                                          [Team Lead]
36                              [Network Administrator]
37                                      [IT Consultant]
Name: job, dtype: object

In [229]:
users.groupby("age").agg({
    "job": list,
    "id": "sum"
})

                                                   job  id
age
22                                  [Graphic Designer]  15
23                    [HR Coordinator, Data Scientist]  35
24              [Frontend Developer, Digital Marketer]  26
25      [Cyber Security Analyst, Recruiter, Recruiter]  71
26                   [UI/UX Designer, Product Manager]  21
27   [Machine Learning Engineer, Content Writer, Fi...  39
28   [Backend Developer, Android Developer, Fronten...  52
29   [Software Developer, Software Developer, Full ...  40
30                    [Data Analyst, Business Analyst]  26
31   [Project Manager, System Analyst, System Analyst]  63
32                  [QA Engineer, Solutions Architect]  23
33                                   [Cloud Architect]  12
34   [DevOps Engineer, Database Administrator, Data...  76
35                                         [Team Lead]   9
36                             [Network Administrator]  26
37                                     [IT Consultant]  19

In [230]:
users.groupby("age", as_index=False)["job"].agg(list) # result is data frame

    age                                                job
0    22                                 [Graphic Designer]
1    23                   [HR Coordinator, Data Scientist]
2    24             [Frontend Developer, Digital Marketer]
3    25     [Cyber Security Analyst, Recruiter, Recruiter]
4    26                  [UI/UX Designer, Product Manager]
5    27  [Machine Learning Engineer, Content Writer, Fi...
6    28  [Backend Developer, Android Developer, Fronten...
7    29  [Software Developer, Software Developer, Full ...
8    30                   [Data Analyst, Business Analyst]
9    31  [Project Manager, System Analyst, System Analyst]
10   32                 [QA Engineer, Solutions Architect]
11   33                                  [Cloud Architect]
12   34  [DevOps Engineer, Database Administrator, Data...
13   35                                        [Team Lead]
14   36                            [Network Administrator]
15   37                                    [IT Consultant]

## Data Cleaning

- removing unwanted data
- Pandas are mainly used for data cleaning

### Dropping irrelavant columns

In [231]:
users.drop(columns=["id"])

                 age                        email                        job
name
1Ravi Kumar       29      1ravi.kumar@example.com         Software Developer
Ravi Kumar        29       ravi.kumar@example.com         Software Developer
Kiran Reddy       32      kiran.reddy@example.com                QA Engineer
Suma Priya        26       suma.priya@example.com             UI/UX Designer
Rahul Sharma      30     rahul.sharma@example.com               Data Analyst
Akhil Verma       27      akhil.verma@example.com  Machine Learning Engineer
Pooja Devi        24       pooja.devi@example.com         Frontend Developer
Sai Teja          31         sai.teja@example.com            Project Manager
Meena Singh       28      meena.singh@example.com          Backend Developer
Aditya Raj        35       aditya.raj@example.com                  Team Lead
Divya Gupta       23      divya.gupta@example.com             HR Coordinator
Harika Nair       27      harika.nair@example.com             Content Writer
Vijay Kumar       33      vijay.kumar@example.com            Cloud Architect
Swathi Rao        25       swathi.rao@example.com     Cyber Security Analyst
Naveen Chandra    29   naveen.chandra@example.com       Full Stack Developer
Niharika Sharma   22  niharika.sharma@example.com           Graphic Designer
Sandeep Joshi     34    sandeep.joshi@example.com            DevOps Engineer
Karthik R         28        karthik.r@example.com          Android Developer
Ritika Jain       26      ritika.jain@example.com            Product Manager
Yashwant Singh    37   yashwant.singh@example.com              IT Consultant
Lavanya B         24        lavanya.b@example.com           Digital Marketer
Rohit Kulkarni    32   rohit.kulkarni@example.com        Solutions Architect
Preethi V         30        preethi.v@example.com           Business Analyst
Suhas Rao         27        suhas.rao@example.com          Financial Analyst
Rohan Mehta       29      rohan.mehta@example.com       Blockchain Developer
Sneha Kapoor      23     sneha.kapoor@example.com             Data Scientist
Anil Pandey       36      anil.pandey@example.com      Network Administrator
Sravani M         28        sravani.m@example.com          Frontend Engineer
Dinesh Varma      31     dinesh.varma@example.com             System Analyst
Anusha Shetty     25    anusha.shetty@example.com                  Recruiter
Mahesh Patil      34     mahesh.patil@example.com     Database Administrator
1Dinesh Varma     31     dinesh.varma@example.com             System Analyst
1Anusha Shetty    25    anusha.shetty@example.com                  Recruiter
1Mahesh Patil     34     mahesh.patil@example.com     Database Administrator

In [232]:
noc_regions = pd.read_csv('./data/noc_regions.csv')
noc_regions

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]

### Handling Missing Data

In [233]:
noc_regions.dropna(subset=["notes"]) # drop not available

     NOC                       region                        notes
1    AHO                      Curacao         Netherlands Antilles
6    ANT                      Antigua          Antigua and Barbuda
7    ANZ                    Australia                  Australasia
26   BOH               Czech Republic                      Bohemia
51   CRT                       Greece                        Crete
88   HKG                        China                    Hong Kong
93   IOA  Individual Olympic Athletes  Individual Olympic Athletes
99   ISV           Virgin Islands, US               Virgin Islands
143  NBO                     Malaysia                 North Borneo
147  NFL                       Canada                 Newfoundland
168  ROT                          NaN         Refugee Olympic Team
175  SCG                       Serbia        Serbia and Montenegro
179  SKN                  Saint Kitts     Turks and Caicos Islands
205  TTO                     Trinidad          Trinidad and Tobago
208  TUV                          NaN                       Tuvalu
210  UAR                        Syria         United Arab Republic
213  UNK                          NaN                      Unknown
223  WIF                     Trinidad       West Indies Federation
224  YAR                        Yemen                  North Yemen
226  YMD                        Yemen                  South Yemen
227  YUG                       Serbia                   Yugoslavia

In [234]:
noc_regions.fillna({"notes":"Yet to add"}) # fill not available

     NOC       region                 notes
0    AFG  Afghanistan            Yet to add
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania            Yet to add
3    ALG      Algeria            Yet to add
4    AND      Andorra            Yet to add
..   ...          ...                   ...
225  YEM        Yemen            Yet to add
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia            Yet to add
229  ZIM     Zimbabwe            Yet to add

[230 rows x 3 columns]

### Fix inconsistent data

In [235]:
noc_regions["region"].replace("Yemen","YEMEN")

0      Afghanistan
1          Curacao
2          Albania
3          Algeria
4          Andorra
          ...
225          YEMEN
226          YEMEN
227         Serbia
228         Zambia
229       Zimbabwe
Name: region, Length: 230, dtype: object

In [236]:
noc_regions["region"] = noc_regions["region"].replace({"Yemen":"YEMEN","Serbia":"SERBIA"}) # multiple & re-assign
noc_regions["region"]

0      Afghanistan
1          Curacao
2          Albania
3          Algeria
4          Andorra
          ...
225          YEMEN
226          YEMEN
227         SERBIA
228         Zambia
229       Zimbabwe
Name: region, Length: 230, dtype: object

### Standardize Text

In [237]:
noc_regions["region"] = noc_regions["region"].str.lower()
noc_regions["region"]

0      afghanistan
1          curacao
2          albania
3          algeria
4          andorra
          ...
225          yemen
226          yemen
227         serbia
228         zambia
229       zimbabwe
Name: region, Length: 230, dtype: object

### Fix Data Types

In [238]:
noc_regions["notes"].astype(bool)

0      True
1      True
2      True
3      True
4      True
       ...
225    True
226    True
227    True
228    True
229    True
Name: notes, Length: 230, dtype: bool

In [239]:
users["id"].astype(bool)

name
1Ravi Kumar        True
Ravi Kumar         True
Kiran Reddy        True
Suma Priya         True
Rahul Sharma       True
Akhil Verma        True
Pooja Devi         True
Sai Teja           True
Meena Singh        True
Aditya Raj         True
Divya Gupta        True
Harika Nair        True
Vijay Kumar        True
Swathi Rao         True
Naveen Chandra     True
Niharika Sharma    True
Sandeep Joshi      True
Karthik R          True
Ritika Jain        True
Yashwant Singh     True
Lavanya B          True
Rohit Kulkarni     True
Preethi V          True
Suhas Rao          True
Rohan Mehta        True
Sneha Kapoor       True
Anil Pandey        True
Sravani M          True
Dinesh Varma       True
Anusha Shetty      True
Mahesh Patil       True
1Dinesh Varma      True
1Anusha Shetty     True
1Mahesh Patil      True
Name: id, dtype: bool

### Remove Duplicates

In [246]:
print(users)
users = users.drop_duplicates()
users

                 id  age                        email  \
name
Ravi Kumar        1   29       ravi.kumar@example.com
Ravi Kumar        1   29       ravi.kumar@example.com
Kiran Reddy       2   32      kiran.reddy@example.com
Suma Priya        3   26       suma.priya@example.com
Rahul Sharma      4   30     rahul.sharma@example.com
Akhil Verma       5   27      akhil.verma@example.com
Pooja Devi        6   24       pooja.devi@example.com
Sai Teja          7   31         sai.teja@example.com
Meena Singh       8   28      meena.singh@example.com
Aditya Raj        9   35       aditya.raj@example.com
Divya Gupta      10   23      divya.gupta@example.com
Harika Nair      11   27      harika.nair@example.com
Vijay Kumar      12   33      vijay.kumar@example.com
Swathi Rao       13   25       swathi.rao@example.com
Naveen Chandra   14   29   naveen.chandra@example.com
Niharika Sharma  15   22  niharika.sharma@example.com
Sandeep Joshi    16   34    sandeep.joshi@example.com
Karthik R        17   28        karthik.r@example.com
Ritika Jain      18   26      ritika.jain@example.com
Yashwant Singh   19   37   yashwant.singh@example.com
Lavanya B        20   24        lavanya.b@example.com
Rohit Kulkarni   21   32   rohit.kulkarni@example.com
Preethi V        22   30        preethi.v@example.com
Suhas Rao        23   27        suhas.rao@example.com
Rohan Mehta      24   29      rohan.mehta@example.com
Sneha Kapoor     25   23     sneha.kapoor@example.com
Anil Pandey      26   36      anil.pandey@example.com
Sravani M        27   28        sravani.m@example.com
Dinesh Varma     28   31     dinesh.varma@example.com
Anusha Shetty    29   25    anusha.shetty@example.com
Mahesh Patil     30   34     mahesh.patil@example.com
Dinesh Varma     28   31     dinesh.varma@example.com
Anusha Shetty    29   25    anusha.shetty@example.com
Mahesh Patil     30   34     mahesh.patil@example.com

                                       job
name
Ravi Kumar              Software Developer
Ravi Kumar              Software Developer
Kiran Reddy                    QA Engineer
Suma Priya                  UI/UX Designer
Rahul Sharma                  Data Analyst
Akhil Verma      Machine Learning Engineer
Pooja Devi              Frontend Developer
Sai Teja                   Project Manager
Meena Singh              Backend Developer
Aditya Raj                       Team Lead
Divya Gupta                 HR Coordinator
Harika Nair                 Content Writer
Vijay Kumar                Cloud Architect
Swathi Rao          Cyber Security Analyst
Naveen Chandra        Full Stack Developer
Niharika Sharma           Graphic Designer
Sandeep Joshi              DevOps Engineer
Karthik R                Android Developer
Ritika Jain                Product Manager
Yashwant Singh               IT Consultant
Lavanya B                 Digital Marketer
Rohit Kulkarni         Solutions Architect
Preethi V                 Business Analyst
Suhas Rao                Financial Analyst
Rohan Mehta           Blockchain Developer
Sneha Kapoor                Data Scientist
Anil Pandey          Network Administrator
Sravani M                Frontend Engineer
Dinesh Varma                System Analyst
Anusha Shetty                    Recruiter
Mahesh Patil        Database Administrator
Dinesh Varma                System Analyst
Anusha Shetty                    Recruiter
Mahesh Patil        Database Administrator

,id,age,email,job
name,,,,
Ravi Kumar,1,29,ravi.kumar@example.com,Software Developer
Kiran Reddy,2,32,kiran.reddy@example.com,QA Engineer
Suma Priya,3,26,suma.priya@example.com,UI/UX Designer
Rahul Sharma,4,30,rahul.sharma@example.com,Data Analyst
Akhil Verma,5,27,akhil.verma@example.com,Machine Learning Engineer
Pooja Devi,6,24,pooja.devi@example.com,Frontend Developer
Sai Teja,7,31,sai.teja@example.com,Project Manager
Meena Singh,8,28,meena.singh@example.com,Backend Developer
Aditya Raj,9,35,aditya.raj@example.com,Team Lead
Divya Gupta,10,23,divya.gupta@example.com,HR Coordinator
Harika Nair,11,27,harika.nair@example.com,Content Writer
Vijay Kumar,12,33,vijay.kumar@example.com,Cloud Architect
Swathi Rao,13,25,swathi.rao@example.com,Cyber Security Analyst
Naveen Chandra,14,29,naveen.chandra@example.com,Full Stack Developer
Niharika Sharma,15,22,niharika.sharma@example.com,Graphic Designer
Sandeep Joshi,16,34,sandeep.joshi@example.com,DevOps Engineer
Karthik R,17,28,karthik.r@example.com,Android Developer
Ritika Jain,18,26,ritika.jain@example.com,Product Manager
Yashwant Singh,19,37,yashwant.singh@example.com,IT Consultant
Lavanya B,20,24,lavanya.b@example.com,Digital Marketer
Rohit Kulkarni,21,32,rohit.kulkarni@example.com,Solutions Architect
Preethi V,22,30,preethi.v@example.com,Business Analyst
Suhas Rao,23,27,suhas.rao@example.com,Financial Analyst
Rohan Mehta,24,29,rohan.mehta@example.com,Blockchain Developer
Sneha Kapoor,25,23,sneha.kapoor@example.com,Data Scientist
Anil Pandey,26,36,anil.pandey@example.com,Network Administrator
Sravani M,27,28,sravani.m@example.com,Frontend Engineer
Dinesh Varma,28,31,dinesh.varma@example.com,System Analyst
Anusha Shetty,29,25,anusha.shetty@example.com,Recruiter
Mahesh Patil,30,34,mahesh.patil@example.com,Database Administrator